### ISSUE TITLE
P-value

### ISSUE THREAD

**Issue by ck37** [American-Institutes-for-Research/wCorr#1]
Hello,

Is it possible to add a p-value to the correlation results?

Thanks,
Chris

**Comment by pdbailey0** [comment]
Yes. Do you have sampling weights, frequency weights, or precision weights?

**Comment by ck37** [comment]
Thanks, I would say that sampling weights are mainly what I use.

**Comment by pdbailey0** [comment]
This would depend on the structure of your survey. wCorr is designed to let you use survey methodology on top of it--it does not perform the survey analysis for you.
